version: '3.8'

services:
  kvrocks:

    image: apache/kvrocks:latest
    
    container_name: kvrocks
    
    restart: always
    
    ports:
      - "6379:6666"
      
    volumes:
      - ./kvrocks_data:/var/lib/kvrocks